### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by liangzhitao** [tufu9441/maupassant-hexo#105]
```
Unhandled rejection TypeError: /Users/liang/Dropbox/HexoSource/themes/maupassant/layout/post.jade:10
    8|     h1.post-title= page.title
    9|     .post-meta= page.date.format('ll')
  > 10|       if page.categories.length > 0
    11|         span= ' | '
    12|         span.category
    13|           for category in page.categories.toArray()

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/Users/liang/Dropbox/HexoSource/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:323:21)
    at eval (eval at <anonymous> (/Users/liang/Dropbox/HexoSource/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1240:22)
    at res (/Users/liang/Dropbox/HexoSource/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at Hexo.jadeRenderer (/Users/liang/Dropbox/HexoSource/node_modules/hexo-renderer-jade/lib/renderer.js:12:27)
    at Hexo.tryCatcher (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/liang/Dropbox/HexoSource/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/liang/Dropbox/HexoSource/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Hi, I occured this problem, did you know how to do with it?
Thank you.

**Comment by tufu9441** [comment]
Sorry I have never met this problem before, try to re-install Hexo and the theme.

**Comment by tufu9441** [comment]
I see you have solved this problem and your blog looks normal now, maybe you can write it here how to deal with it, thanks!

**Comment by liangzhitao** [comment]
@tufu9441 sorry, I have not solved it yet, I just choosed NexT.Pisces instead.

**Comment by tufu9441** [comment]
Sorry I just made a mistake.
