### ISSUE TITLE
hexo-renderer-sass不能正常下载

### ISSUE THREAD

**Issue by ryangun** [tufu9441/maupassant-hexo#122]
您好，最近我发现自己的博客编译出问题了，无法编译出style.css，界面没有样式了。

看报错，貌似是hexo-renderer-sass出问题了，告诉我没找到这样的包，但博客我用了好一段时间了，都没有问题，不知道是不是和我最近更新node版本或者是npm的版本有关。

下面是报错信息，谢谢！

``` bash
➜  blog2 sudo hexo server
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/bunyan/lib/bunyan.js:34:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo/lib/hexo/create_logger.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/bunyan/lib/bunyan.js:34:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo/lib/hexo/create_logger.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/bunyan/lib/bunyan.js:34:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo/lib/hexo/create_logger.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' }
ERROR Plugin load failed: hexo-renderer-sass
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-renderer-sass/index.js:1:79
    at /Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:615:18)
    at /Users/ganzhonghuan/ryangun/www/blog2/node_modules/hexo-fs/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/ganzhonghuan/ryangun/www/blog2/node_modules/graceful-fs/graceful-fs.js:76:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

**Comment by tufu9441** [comment]
升级node版本后最好重新安装一下Hexo。或者恢复到以前版本试试。

**Comment by tufu9441** [comment]
或者重新安装hexo-renderer-sass，从npm淘宝镜像安装或者给终端挂代理。
