### ISSUE TITLE
unknown block tag: gp

### ISSUE THREAD

**Issue by ehlxr** [tufu9441/maupassant-hexo#172]
楼主， hexo g的时候报一下错误，请问咋办啊
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: gp
    at Object.exports.prettifyError (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:326:21)
    at E:\ehlxr\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:475:18)
    at new Promise (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (E:\ehlxr\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\ehlxr\Hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\ehlxr\Hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 1, Column 2]
  unknown block tag: gp
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: gp
    at Object.exports.prettifyError (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (E:\ehlxr\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:326:21)
    at E:\ehlxr\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:475:18)
    at new Promise (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (E:\ehlxr\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\ehlxr\Hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\ehlxr\Hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\ehlxr\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by tufu9441** [comment]
Hexo环境或者插件没有正确安装的原因，重新安装试试。

**Comment by ehlxr** [comment]
谢谢，最后发现是文章中有“{% gp”这样的特殊字符导致的
