### ISSUE TITLE
打开self_search时生成HTML报错

### ISSUE THREAD

**Issue by zhufuhua** [tufu9441/maupassant-hexo#202]
Unhandled rejection TypeError: XXXXX/Blog/themes/maupassant/layout/_partial/after_footer.jade:53
    51|      var path = '#{config.root}' + search_path;
    52|      searchFunc(path, 'local-search-input', 'local-search-result');
  > 53|
    54| if theme.google_analytics
    55|   script.
    56|     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

Cannot read property 'path' of undefined
    at eval (eval at exports.compile (XXXXX/Blog/node_modules/jade/lib/index.js:218:8), <anonymous>:909:75)
    at eval (eval at exports.compile (XXXXX/Blog/node_modules/jade/lib/index.js:218:8), <anonymous>:1094:22)
    at res (XXXXX/Blog/node_modules/jade/lib/index.js:219:38)
    at Theme._View.View._compiled (XXXXX/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (XXXXX/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at XXXXX/Blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (XXXXX/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at XXXXX/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (XXXXX/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by noparkinghere** [comment]
确定是否正确安装hexo-generator-search插件使用？！

**Comment by tufu9441** [comment]
@zhufuhua 我看你博客已经可以正常访问了，能说一下是如何解决的吗？

**Comment by zhufuhua** [comment]
self_search 现在可以用了么？我博客上没有开self_search，上面的搜索框是baidu_search.

**Comment by tufu9441** [comment]
嗯，我看到了。self_search一直没有改动过。

**Comment by tufu9441** [comment]
我最近看着更新一下self_search到作者的新版本，然后你可以再试试。

**Comment by tufu9441** [comment]
你之前有按照说明安装并配置hexo-generator-search插件吗？
https://github.com/PaicHyperionDev/hexo-generator-search

**Comment by zhufuhua** [comment]
有按照配置装过 hexo-generator-search 插件的，后面我重新试一下看看 @tufu9441

**Comment by tufu9441** [comment]
我说错了，hexo-generator-search是本地安装的插件，应该是你在自己电脑上更新后试试。

**Comment by zhufuhua** [comment]
有装的
npm list --depth=0
hexo-site@0.0.0 /Users/XXXXXX
├── hexo@3.2.2
├── hexo-generator-search@2.1.1

**Comment by tufu9441** [comment]
你后来有试成功过么？或者安`hexo-generator-searchdb`这个插件也试一下。
