### ISSUE TITLE
生成报错

### ISSUE THREAD

**Issue by DavidSheh** [tufu9441/maupassant-hexo#316]
运行命令 hexo generate后直接报错，试了好几遍。试了一下其他主题是正常的。不知道啥情况？

Unhandled rejection TypeError: /Users/xxx/hexo_blog/Hexo/themes/maupassant/layout/post.jade:42
    40|     if theme.shareto == true
    41|       script(type='text/javascript', src=url_for(theme.js) + '/share.js' + '?v=' + theme.version, async)
  > 42|       a.article-share-link(data-url='#{page.permalink}', data-id='#{page._id}', data-qrcode=qrcode(page.permalink))= __('shareto')
    43|     include _partial/tag
    44|     include _partial/post_nav
    45|     if theme.duoshuo

qrcode is not a function
    at eval (eval at exports.compile (/Users/davidsheh/hexo_blog/Hexo/node_modules/jade/lib/index.js:218:8), <anonymous>:587:168)
    at eval (eval at exports.compile (/Users/davidsheh/hexo_blog/Hexo/node_modules/jade/lib/index.js:218:8), <anonymous>:1680:22)
    at res (/Users/davidsheh/hexo_blog/Hexo/node_modules/jade/lib/index.js:219:38)
    at Theme._View.View._compiled (/Users/davidsheh/hexo_blog/Hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/davidsheh/hexo_blog/Hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/davidsheh/hexo_blog/Hexo/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/Users/davidsheh/hexo_blog/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/davidsheh/hexo_blog/Hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/davidsheh/hexo_blog/Hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:431:10)
    at resume_ (_stream_readable.js:811:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by tufu9441** [comment]
现在更新一下就好了。新版本要使用shareto: true的话需要安装hexo-helper-qrcode。
