### ISSUE TITLE
after_footer.pug 运行时错误

### ISSUE THREAD

**Issue by Smlight** [tufu9441/maupassant-hexo#358]
通过修改`_config.yaml`文件开启`self_search`后，再`hexo s`出现如下错误：

```
Unhandled rejection TypeError: D:\Git\Blog\themes\maupassant\layout\_partial\after_footer.pug:34
    32|   script(type='text/javascript', src=url_for(theme.js) + '/search.js' + '?v=' + theme.version)
    33|   script.
  > 34|      var search_path = '#{config.search.path}';
    35|      if (search_path.length == 0) {
    36|         search_path = 'search.xml';
    37|      }

Cannot read property 'path' of undefined
    at eval (eval at wrap (D:\Git\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:742:71)
    at template (eval at wrap (D:\Git\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:855:268)
    at Theme._View.View._compiled (D:\Git\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\Git\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Git\Blog\node_modules\hexo\lib\hexo\index.js:390:29
    at tryCatcher (D:\Git\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Git\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Git\Blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

版本信息如下：
```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

**Comment by tufu9441** [comment]
是否在Hexo根目录下的_config.yml中配置好路径：
```
search:
  path: search.xml
  field: post
```

**Comment by Smlight** [comment]
terribly sorry about that. 
已经可以了，我确实不知道还要加这个。。。

**Comment by Smlight** [comment]
又出现一个问题。。。
搜出来的结果没用，所有链接都是当前页面的url

**Comment by tufu9441** [comment]
我又测试了一下并未出现这种情况，你确定依赖插件都安装好了，主题也是最新版本？

**Comment by hbxjw119** [comment]
@Smlight 你要确认下，生成的search.xml文件中，url字段是否有误，如果是形如`<url>//your/path</url>`，这样链接出来就有问题，自己改下，去掉一个斜杠

**Comment by tufu9441** [comment]
@Smlight #361 中也提到了修改search.xml文件中链接形式的方法。

**Comment by Smlight** [comment]
@tufu9441 谢谢！我也是把link标签改成url标签就正常了。

就此关闭。
