### ISSUE TITLE
关于post_copyright的错误

### ISSUE THREAD

**Issue by ninanxiaoguai** [tufu9441/maupassant-hexo#407]
win10系统 打不开文章内容，谢谢~
Unhandled rejection TypeError: H:\HEXO\themes\maupassant\layout\post.pug:43
    41|       iframe(src='/donate/?AliPayQR=' + theme.donate.alipay_qr + '&WeChatQR=' + theme.donate.wech                             at_qr + '&GitHub=' + theme.donate.github + '&BTCQR=' + theme.donate.btc_qr + '&BTCKEY='+ theme.donate.btc                             _key + '&PayPal=' + theme.donate.paypal_url, style='overflow-x:hidden; overflow-y:hidden; border:0xp none                              #fff; min-height:240px; width:100%;', frameborder='0', scrolling='no')
    42|
  > 43|     if theme.post_copyright.enable == true
    44|       div
    45|         ul.post-copyright
    46|           li.post-copyright-author

Cannot read property 'enable' of undefined
    at eval (eval at wrap (H:\HEXO\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:392:26)
    at template (eval at wrap (H:\HEXO\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1319:268)
    at Theme._View.View._compiled.locals [as _compiled] (H:\HEXO\node_modules\hexo\lib\theme\view.js:124:                             48)
    at Theme._View.View.View.render (H:\HEXO\node_modules\hexo\lib\theme\view.js:29:15)
    at route.set (H:\HEXO\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (H:\HEXO\node_modules\bluebird\js\release\util.js:16:23)
    at H:\HEXO\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\HEXO\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by johnpoint** [comment]
不妨将您的配置文件
post_copyright:
段落发出来看看？
