### ISSUE TITLE
shareto按钮无法加载的错误，提示qrcode is not a function

### ISSUE THREAD

**Issue by xhxt2008** [tufu9441/maupassant-hexo#409]
详细报错信息

```
`INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: F:\code\xhxt2008.github.io\themes\maupassant\layo                                                                                                                                  ut\post.pug:62
    60|     if theme.shareto == true
    61|       script(type='text/javascript', src=url_for(theme.js) + '/share.js'                                                                                                                                   + '?v=' + theme.version, async)
  > 62|       a.article-share-link(data-url=page.permalink, data-id=page._id, da                                                                                                                                  ta-qrcode=qrcode(page.permalink))= __('shareto')
    63|
    64|     include _partial/tag.pug
    65|     include _partial/post_nav.pug

qrcode is not a function
    at eval (eval at wrap (F:\code\xhxt2008.github.io\node_modules\pug-runtime\w                                                                                                                                  rap.js:6:10), <anonymous>:441:183)
    at template (eval at wrap (F:\code\xhxt2008.github.io\node_modules\pug-runti                                                                                                                                  me\wrap.js:6:10), <anonymous>:1321:268)
    at Theme._View.View._compiled.locals [as _compiled] (F:\code\xhxt2008.github                                                                                                                                  .io\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (F:\code\xhxt2008.github.io\node_modules\hex                                                                                                                                  o\lib\theme\view.js:29:15)
    at route.set (F:\code\xhxt2008.github.io\node_modules\hexo\lib\hexo\index.js                                                                                                                                  :386:29)
    at tryCatcher (F:\code\xhxt2008.github.io\node_modules\bluebird\js\release\u                                                                                                                                  til.js:16:23)
    at F:\code\xhxt2008.github.io\node_modules\bluebird\js\release\method.js:15:                                                                                                                                  34
    at RouteStream._read (F:\code\xhxt2008.github.io\node_modules\hexo\lib\hexo\                                                                                                                                  router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`
```

**Comment by tufu9441** [comment]
安装hexo-helper-qrcode了没
