### ISSUE TITLE
运行npm install hexo-renderer-sass --save出错，Error: EACCES: permission denied

### ISSUE THREAD

**Issue by JaredLees** [tufu9441/maupassant-hexo#418]
`Unable to save binary /Users/a/Documents/github/blog/node_modules/node-sass/vendor/darwin-x64-64 : { Error: EACCES: permission denied, mkdir '/Users/a/Documents/github/blog/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:874:3)
    at sync (/Users/a/Documents/github/blog/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/a/Documents/github/blog/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/a/Documents/github/blog/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/a/Documents/github/blog/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/Users/a/Documents/github/blog/node_modules/node-sass/vendor' }`

**Comment by JaredLees** [comment]
好吧，我找到解决方法了。如下：
`sudo npm install node-sass --unsafe-perm --save-dev`
