### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined 生成报错

### ISSUE THREAD

**Issue by wangzzu** [tufu9441/maupassant-hexo#443]
下载的最新版，在 mac 上生成时，有以下报错信息，不知道该怎么解决？

`
INFO  Start processing
ERROR Process failed: layout/archive.pug
TypeError: Cannot read property 'compile' of undefined
    at Theme._View.View.View._precompile (/Users/matt/git/matt33/node_modules/hexo-inject/lib/patch/view.js:27:25)
    at Theme._View.View.View (/Users/matt/git/matt33/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/matt/git/matt33/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/matt/git/matt33/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/matt/git/matt33/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/matt/git/matt33/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/matt/git/matt33/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/matt/git/matt33/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/matt/git/matt33/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
`

**Comment by tufu9441** [comment]
只能建议重新安装Hexo和各插件了……

**Comment by wangzzu** [comment]
已经解决了，但是忘记怎么解决的了...
大概记得是有其他的异常日志，根据异常日志去解决
