### ISSUE TITLE
plugin load failed

### ISSUE THREAD

**Issue by tbago** [tufu9441/maupassant-hexo#476]
ERROR Plugin load failed: hexo-renderer-sass
Error: Missing binding /Users/tbago/blog/hexo/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/Users/tbago/blog/hexo/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/tbago/blog/hexo/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/tbago/blog/hexo/node_modules/hexo-renderer-sass/lib/renderer.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/Users/tbago/blog/hexo/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/tbago/blog/hexo/node_modules/hexo-renderer-sass/index.js:4:20
    at /Users/tbago/blog/hexo/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/tbago/blog/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tbago/blog/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/tbago/blog/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/tbago/blog/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/tbago/blog/hexo/node_modules/bluebird/js/release/promise.js:729:18)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

**Comment by tufu9441** [comment]
重装插件或者Hexo，或者检查网络，插件安装问题跟主题无关。

**Comment by tbago** [comment]
开始有警告是可以正常的，后来我做了hexo clean，然后再运行就显示异常了。

**Comment by tbago** [comment]
现在试了下，可以了，首先更新了node.js,npm,然后重装了hexo和hexo-renderer-pug还有hexo-renderer-sass。
