### ISSUE TITLE
kr-KR.yml error

### ISSUE THREAD

**Issue by dynaguy1** [tufu9441/maupassant-hexo#67]
```bash
[root@hexo hexoblog]# hexo g && hexo s
ERROR Process failed: languages/kr-KR.yml
YAMLException: end of the stream or a document separator is expected at line 1, column 16:
    reading_label: %s 의 게시물 모음
                   ^
    at generateError (/root/hexoblog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/root/hexoblog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDocument (/root/hexoblog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1508:5)
    at loadDocuments (/root/hexoblog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/root/hexoblog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Hexo.yamlHelper (/root/hexoblog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /root/hexoblog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/hexoblog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by luozongtong123** [comment]
reading_label: '%s 의 게시물 모음'

**Comment by tufu9441** [comment]
@luozongtong123 Thanks! Fixed now.
