### ISSUE TITLE
maupassant hexo g failed

### ISSUE THREAD

**Issue by jpxiong** [tufu9441/maupassant-hexo#90]
Help solve the issue.

```
$ hexo g
INFO  Start processing
ERROR Process failed: layout/archive.jade
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
ERROR Process failed: layout/post.jade
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jerikc/workdir/myworkspace/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

....

INFO  Files loaded in 1.44 s
WARN  No layout: 2016/04/09/hello-world/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2016/index.html
WARN  No layout: archives/2016/04/index.html
WARN  No layout: index.html

```

**Comment by tufu9441** [comment]
See #84
